lang: en
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

#scholar:
#  style: modern-language-association
#  source: ./assets/publications
postcss:
  cache: false

collections:
  pages:
    output: true
    permalink: /:title/
  news:
    output: true
    permalink: /:collection/:slug/
  projects:
    output: true
    permalink: /:collection/:title/
  education:
    output: false
  certificates:
    output: false
  experience:
    output: false
defaults:
  -
    scope:
      path: "_projects" 
    values:
      layout: "projects"
  -
    scope:
      path: "_news" 
    values:
      layout: "news"
destignation: "docs"
exclude:
- yarn.lock
- package.json
