lang: en
url: "https://nicofirst1.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Nicolo' Brandizzi" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

#scholar:
#  style: modern-language-association
#  source: ./assets/publications
postcss:
  cache: false
sass:
  sass_dir: _scss

collections:
  blog:
    output: true
    permalink: /blog/:slug/
  pages:
    output: true
    permalink: /:title/
  news:
    output: true
    permalink: /:collection/:slug/
  projects:
    output: true
    permalink: /:collection/:title/
  education:
    output: false
  certificates:
    output: false
  experience:
    output: false
  secret_drafts:
    output: true
    permalink: /secret-drafts/:slug/
defaults:
  - scope:
      path: "_projects"
    values:
      layout: "projects"
  - scope:
      path: "_secret_drafts" # This applies to all files in the _secret_drafts folder
    values:
      layout: "news" # Use the same layout as the news collection
  - scope:
      path: "_news"
    values:
      layout: "news"
  - scope:
      path: ""
      type: blog
    values:
      layout: "news"
destination: _site
exclude:
  - yarn.lock
  - package.json
