lang: en
url: "https://nicofirst1.github.io"
baseurl: "" # user site => empty
title: "Nicolo' Brandizzi"

plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  sass_dir: _scss

# OUTPUT: let Actions upload _site (don’t write to docs/)
destination: _site

collections:
  blog:
    output: true
    permalink: /blog/:slug/
  news:
    output: true
    permalink: /:collection/:slug/
  projects:
    output: true
    permalink: /:collection/:title/
  pages:
    output: true
    permalink: /:title/
  education:
    output: false
  certificates:
    output: false
  experience:
    output: false
  secret_drafts:
    output: true
    permalink: /secret-drafts/:slug/

defaults:
  - scope: { path: "_news" }
    values: { layout: "news" }
  - scope: { path: "", type: blog }
    values: { layout: "news" }

exclude:
  - node_modules
  - _site
  - docs
  - package-lock.json
  - yarn.lock
